language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "dfs-charts;' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: dfs-charts # see README
  api_key:
    secure: IzGUm69ymskmCUX8k5GMCvcg2oX6qa+VhZGHX/608AnxaelA7u/3wLMOZD/HnMx//BWQAZi96nb/ELxhaF0DzTbxtK0lE3cqbbSodLk5EP0kCajP8SA1GPqJil1cZUVflFyrGrB+dDZHnSPIrOdy9MGrCH8OJGi0YyLMolHjwl8P/bvL9w/MAU05VHEPva4o1ifIkPtcFFXpJU8ls+gXNoImmMZpSOUA4kPUh7oE0WBtnVFYrP4ldWolIzaBJh1d7fUuqJ8443qQlfjMnF0w9z1xfon0lPYoE4On2ebTKYHEJYY7ryGyBjBCaSvf0IJHbOmWJscV87C1XtadNP84/3riY1cq+61BSmmjWtgAyUaCvGv9/FbrogzXo46nv/YPGjeZ2a25chfyECBbkBstoBWMoOecLjivfSfHNRLExEASlqSQq/x54pd0R/cVPKLXYrLA1M2qMja8du6ryBjAs6SZKKl/pifQKKGANqauaUILCdBNi+zswYo1/+cp82EcJHLQpDGu9nTIpqTEfqnNbDlmnMXriSMV4TQpOTklkwxOfRIHZsZXUOS0L067I2uRX1lBuJArm8+i5TIwbkC4Zjls1ccJuuNnkB3wx13CwAHCago2tRR2mMVEI4eJAG7tlhQCG9nk5Taw8JSqkTKjUXmU3sgp9rrTtvcaVbAz5K4= # see README
